project:
  type: website
  output-dir: docs

website:
  title: "Victoria Cutler"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd
      - resources.qmd
      - href: posts.qmd
        text: Blogs
      - href: resume/vc_resume.pdf
        text: resume
      - icon: github
        href: https://github.com/victoriacutler
      - icon: twitter
        href: https://twitter.com/VictoriaECutler
      - icon: linkedin
        href: https://www.linkedin.com/in/victoria-cutler/
      - icon: envelope
        href: mailto:victoriacutler123@gmail.com

format:
  html:
    theme: 
      - mystyles.scss
    toc: true

editor: visual

