project:
  type: website
  output-dir: docs

website:
  title: "Victoria Cutler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd
      - resources.qmd
      - href: posts.qmd
        text: Blogs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

