---
title: "Is Rooftop Solar Equitable?"
description: "this is a description for XXX"
author:
  - name: Victoria Cutler
    url: https://victoriacutler.github.io # can also add orchid id under here
    affiliation: MEDS 
    affiliation-url: https://ucsb-meds.github.io
date: 2022-10-24
categories: [MEDS, test, R]
citation:
  url: https://victoriacutler.github.io/posts/2022-12-22-solar-equity/
bibliography: references.bib
draft: false # "true" will mean this is a draft post so it wont show up on my site
format:
  html:
    code-fold: true
    code-summary: "code dropdown"
---

# Background

What you may already know of rooftop solar, is that it is a clean and often financially savvy way to supplement energy consumption. In California, customers can effectively "sell" back the electricity they generate at the same rate they would buy it at. Put differently, utilities are buying electricity at the rate that they sell it at, even while cheaper wholesale rates for solar are on the market. Who "pays" for this more expensive electricity that utilities are buying? The short answer is that customers without rooftop solar, typically lower-income customers, are paying. On November 10th 2022, the California Public Utilities Commission (CPUC) put forth a proposal that disincentives solar adoption and production: rolling back compensation and decreasing the maximum allowable install capacity (solar panel wattage). In the previous proposal in December 2021, the CPUC suggested tacking on a monthly fee to the bills of homes with rooftop solar, but this clause has since been walked back [@penn2022]

Stakeholders in the energy industry all feel very differently on matter. And the question boils down to: how much should homeowners be paid for their rooftop solar exports and how much should rooftop solar users pay for grid infrastructure?

The current proposal is out for public comment through XX until the CPUC's five members take the proposal to a vote.

-   **add some history about the incentives in california/maybe nation wide**

-   **talk about the equity concerns with renters and potentially language barriers and how it became a tax on the rich**

# Objective

In this post, I aim to explore, nationwide, if income can be a statistically significant predictor in rooftop solar adoption, and to what degree income differentials are at (significant difference in income means between solar and non solar customers). And, specifically, to explore this relationship in California, where the California Public Utilities Commission is likely to lower financial incentives to rooftop solar adoption due largely to equity concerns.

# Methods

-   checked to see if OLS assumptions were met

# Results

```{r}

```

# Discussion

Hi this is my class example blog post

Here is some more text [@lehmann2007]

here i am giong to cite my blog post from last year
